// <auto-generated />
namespace AutoService.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class basket_start : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basket_start));
        
        string IMigrationMetadata.Id
        {
            get { return "202002241433014_basket_start"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
