// <auto-generated />
namespace AutoService.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class discv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discv5));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191940021_discv5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
