// <auto-generated />
namespace AutoService.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newCarStorage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newCarStorage));
        
        string IMigrationMetadata.Id
        {
            get { return "202004251411510_newCarStorage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
